# Generated by Django 5.2.5 on 2025-09-02 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BatchDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_name', models.CharField(max_length=255)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('owner', models.CharField(max_length=150)),
                ('total_images', models.IntegerField()),
                ('total_eggs', models.IntegerField()),
                ('total_hatched', models.IntegerField()),
            ],
            options={
                'db_table': 'batch_details',
            },
        ),
        migrations.CreateModel(
            name='ImageDetails',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image_name', models.CharField(max_length=255)),
                ('total_eggs', models.IntegerField()),
                ('total_hatched', models.IntegerField()),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('img_type', models.CharField(choices=[('MICRO', 'Micro'), ('MACRO', 'Macro')], max_length=10)),
                ('allow_collection', models.BooleanField(default=True)),
                ('batch', models.ForeignKey(db_column='batch_id', on_delete=django.db.models.deletion.CASCADE, to='egglytics.batchdetails')),
            ],
            options={
                'db_table': 'image_details',
            },
        ),
        migrations.CreateModel(
            name='AnnotationPoints',
            fields=[
                ('point_id', models.AutoField(primary_key=True, serialize=False)),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('is_original', models.BooleanField(default=True)),
                ('image', models.ForeignKey(db_column='image_id', on_delete=django.db.models.deletion.CASCADE, to='egglytics.imagedetails')),
            ],
            options={
                'db_table': 'annotation_points',
            },
        ),
    ]
