# Generated by Django 5.2.5 on 2026-04-10 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnnotationPolygon',
            fields=[
                ('polygon_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_original', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'annotation_polygons',
            },
        ),
        migrations.CreateModel(
            name='BatchDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_name', models.CharField(max_length=255)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('owner', models.CharField(default='Incognito', max_length=150)),
                ('total_images', models.IntegerField()),
                ('total_eggs', models.IntegerField()),
                ('total_hatched', models.IntegerField()),
                ('is_complete', models.BooleanField()),
                ('has_fail_present', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'batch_details',
            },
        ),
        migrations.CreateModel(
            name='AnnotationPolygonPoint',
            fields=[
                ('point_id', models.AutoField(primary_key=True, serialize=False)),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('order_index', models.IntegerField()),
                ('polygon', models.ForeignKey(db_column='polygon_id', on_delete=django.db.models.deletion.CASCADE, related_name='points', to='egglytics.annotationpolygon')),
            ],
            options={
                'db_table': 'annotation_polygon_points',
                'ordering': ['order_index'],
            },
        ),
        migrations.CreateModel(
            name='ImageDetails',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=255)),
                ('total_eggs', models.IntegerField()),
                ('total_hatched', models.IntegerField()),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('img_type', models.CharField(choices=[('MICRO', 'Micro'), ('MACRO', 'Macro')], max_length=10)),
                ('is_processed', models.BooleanField()),
                ('is_validated', models.BooleanField()),
                ('model_used', models.CharField(max_length=255)),
                ('image_version', models.IntegerField(default=1)),
                ('batch', models.ForeignKey(db_column='batch_id', on_delete=django.db.models.deletion.CASCADE, to='egglytics.batchdetails')),
            ],
            options={
                'db_table': 'image_details',
            },
        ),
        migrations.CreateModel(
            name='AnnotationRect',
            fields=[
                ('rect_id', models.AutoField(primary_key=True, serialize=False)),
                ('x_init', models.IntegerField()),
                ('y_init', models.IntegerField()),
                ('x_end', models.IntegerField()),
                ('y_end', models.IntegerField()),
                ('is_original', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('image', models.ForeignKey(db_column='image_id', on_delete=django.db.models.deletion.CASCADE, to='egglytics.imagedetails')),
            ],
            options={
                'db_table': 'annotation_rects',
            },
        ),
        migrations.AddField(
            model_name='annotationpolygon',
            name='image',
            field=models.ForeignKey(db_column='image_id', on_delete=django.db.models.deletion.CASCADE, to='egglytics.imagedetails'),
        ),
        migrations.CreateModel(
            name='AnnotationPoints',
            fields=[
                ('point_id', models.AutoField(primary_key=True, serialize=False)),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('is_original', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('image', models.ForeignKey(db_column='image_id', on_delete=django.db.models.deletion.CASCADE, to='egglytics.imagedetails')),
            ],
            options={
                'db_table': 'annotation_points',
            },
        ),
        migrations.CreateModel(
            name='VerifiedGrids',
            fields=[
                ('grid_id', models.AutoField(primary_key=True, serialize=False)),
                ('x', models.PositiveIntegerField()),
                ('y', models.PositiveIntegerField()),
                ('image', models.ForeignKey(db_column='image_id', on_delete=django.db.models.deletion.CASCADE, to='egglytics.imagedetails')),
            ],
            options={
                'db_table': 'verified_grids',
                'unique_together': {('image', 'x', 'y')},
            },
        ),
    ]
