# Generated by Django 5.2.5 on 2025-09-15 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egglytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchdetails',
            name='is_complete',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagedetails',
            name='is_processed',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
