# Generated by Django 5.2.5 on 2025-09-22 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egglytics', '0002_batchdetails_is_complete_imagedetails_is_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotationpoints',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
