# Generated by Django 5.2.5 on 2025-10-19 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egglytics', '0003_annotationpoints_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchdetails',
            name='has_fail_present',
            field=models.BooleanField(default=False),
        ),
    ]
