# Generated by Django 5.2.5 on 2026-01-12 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egglytics', '0004_batchdetails_has_fail_present'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagedetails',
            name='is_validated',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
