# Generated by Django 5.2.5 on 2026-01-14 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egglytics', '0005_imagedetails_is_validated'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchdetails',
            name='model_used',
            field=models.CharField(default='sample_model', max_length=255),
            preserve_default=False,
        ),
    ]
