# Generated by Django 5.2.5 on 2026-01-14 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egglytics', '0006_batchdetails_model_used'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batchdetails',
            name='model_used',
        ),
        migrations.AddField(
            model_name='imagedetails',
            name='model_used',
            field=models.CharField(default='HELLO WORLD', max_length=255),
            preserve_default=False,
        ),
    ]
