# Generated by Django 5.2.5 on 2026-01-18 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egglytics', '0007_remove_batchdetails_model_used_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnotationRect',
            fields=[
                ('point_id', models.AutoField(primary_key=True, serialize=False)),
                ('x_init', models.IntegerField()),
                ('y_init', models.IntegerField()),
                ('x_end', models.IntegerField()),
                ('y_end', models.IntegerField()),
                ('is_original', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('image', models.ForeignKey(db_column='image_id', on_delete=django.db.models.deletion.CASCADE, to='egglytics.imagedetails')),
            ],
            options={
                'db_table': 'annotation_rects',
            },
        ),
    ]
