# Generated by Django 5.2.5 on 2026-01-19 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('egglytics', '0008_annotationrect'),
    ]

    operations = [
        migrations.RenameField(
            model_name='annotationrect',
            old_name='point_id',
            new_name='rect_id',
        ),
    ]
