# Generated by Django 5.2.5 on 2026-01-28 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('egglytics', '0009_rename_point_id_annotationrect_rect_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagedetails',
            name='allow_collection',
        ),
    ]
