# Generated by Django 5.2.5 on 2026-01-31 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egglytics', '0010_remove_imagedetails_allow_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagedetails',
            name='image_version',
            field=models.IntegerField(default=1),
        ),
    ]
