# Generated by Django 5.2.5 on 2026-02-05 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egglytics', '0011_imagedetails_image_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagedetails',
            name='file_path',
            field=models.CharField(default='1', max_length=255),
            preserve_default=False,
        ),
    ]
