# Generated by Django 5.2.5 on 2026-02-06 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egglytics', '0012_imagedetails_file_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerifiedGrids',
            fields=[
                ('grid_id', models.AutoField(primary_key=True, serialize=False)),
                ('x', models.PositiveIntegerField()),
                ('y', models.PositiveIntegerField()),
                ('image', models.ForeignKey(db_column='image_id', on_delete=django.db.models.deletion.CASCADE, to='egglytics.imagedetails')),
            ],
            options={
                'db_table': 'verified_grids',
                'unique_together': {('image', 'x', 'y')},
            },
        ),
    ]
