# Generated by Django 5.2.5 on 2026-03-09 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egglytics', '0013_verifiedgrids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchdetails',
            name='owner',
            field=models.CharField(default='Incognito', max_length=150),
        ),
    ]
