# Generated by Django 5.2.3 on 2026-03-11 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('egglytics', '0014_alter_batchdetails_owner'),  # replace with your last migration
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE image_details DROP COLUMN preview_path;",
            reverse_sql="ALTER TABLE image_details ADD COLUMN preview_path varchar(255);"
        ),
    ]