# Generated by Django 5.2.3 on 2026-03-12 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egglytics', '0015_auto_20260311_1420'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnotationPolygon',
            fields=[
                ('polygon_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_original', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('image', models.ForeignKey(db_column='image_id', on_delete=django.db.models.deletion.CASCADE, to='egglytics.imagedetails')),
            ],
            options={
                'db_table': 'annotation_polygons',
            },
        ),
        migrations.CreateModel(
            name='AnnotationPolygonPoint',
            fields=[
                ('point_id', models.AutoField(primary_key=True, serialize=False)),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('order_index', models.IntegerField()),
                ('polygon', models.ForeignKey(db_column='polygon_id', on_delete=django.db.models.deletion.CASCADE, related_name='points', to='egglytics.annotationpolygon')),
            ],
            options={
                'db_table': 'annotation_polygon_points',
                'ordering': ['order_index'],
            },
        ),
    ]
